[package]
distribution = "2201.9.0"
name = "hl7v2_to_fhir"
org = "healthcare_samples"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
name = "health.hl7v2.utils.v2tofhirr4"
org = "ballerinax"
version = "2.2.2"

[[dependency]]
name = "health.hl7v2commons"
org = "ballerinax"
version = "1.1.1"
