[package]
org = "healthcare_samples"
name = "hl7v2_to_json"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[dependencies]
org = "ballerinax"
name = "health.hl7v23"
version = "3.0.2"
