[package]
org = "healthcare_samples"
name = "hl7v2_to_medcom_fhir"
version = "1.0.0"
distribution = "2201.12.3"

[build-options]
# optimizeDependencyCompilation = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.medcom240"
version = "1.0.0"
repository = "local"
